export enum ActionTypeStates {
  INPROGRESS = '_INPROGRESS',
  SUCCESS = '_SUCCESS',
  FAIL = '_FAIL'
}

enum ActionTypeKeys {
  LOGIN_INPROGRESS = 'LOGIN_INPROGRESS',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',

  LOGOUT_INPROGRESS = 'LOGOUT_INPROGRESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGOUT_FAIL = 'LOGOUT_FAIL',

  SIGNUP_INPROGRESS = 'SIGNUP_INPROGRESS',
  SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
  SIGNUP_FAIL = 'SIGNUP_FAIL',

  ACTION_INPROGRESS = 'ACTION_INPROGRESS',
  ACTION_FAIL = 'ACTION_FAIL',

  ALL_USERS = 'ALL_USERS',
  EDIT_USER = 'EDIT_USER',
  ADD_USER = 'ADD_USER',

  ADD_FRIEND = 'ADD_FRIEND',

  ADD_CHALLENGE = 'ADD_CHALLENGE',
  EDIT_CHALLENGE = 'EDIT_CHALLENGE',
  ALL_CHALLENGES = 'ALL_CHALLENGES',

  ADD_SCORECARD = 'ADD_SCORECARD',

  ADD_ACTIVITY = 'ADD_ACTIVITY',

}

export default ActionTypeKeys;
