module.exports = {
  logInSchema: require('./logInSchema'),
  createUserSchema: require('./createUserSchema'),
  createPendingFriendshipSchema: require('./createPendingFriendshipSchema'),
  getUserSchema: require('./getUserSchema'),
  getUserFriendsListSchema: require('./getUserFriendsListSchema'),
  getUserChallengesSchema: require('./getUserChallengesSchema'),
  getUserActivitiesSchema: require('./getUserActivitiesSchema'),
  getChallengeSchema: require('./getChallengeSchema'),
  createChallengeSchema: require('./createChallengeSchema'),
  createActivitySchema: require('./createActivitySchema'),
  editChallengeSchema: require('./editChallengeSchema'),
  getChallengeParticipantsSchema: require('./getChallengeParticipantsSchema'),
  getChallengeActivitiesSchema: require('./getChallengeActivitiesSchema'),
  getChallengeScorecardsSchema: require('./getChallengeScorecardsSchema'),
};
